
package northwind.domain.customer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomersPort", targetNamespace = "http://domain.northwind/customer")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomersPort {


    /**
     * 
     * @param getCustomerRequest
     * @return
     *     returns northwind.domain.customer.GetCustomerResponse
     */
    @WebMethod(operationName = "GetCustomer")
    @WebResult(name = "GetCustomerResponse", targetNamespace = "http://domain.northwind/customer", partName = "GetCustomerResponse")
    public GetCustomerResponse getCustomer(
        @WebParam(name = "GetCustomerRequest", targetNamespace = "http://domain.northwind/customer", partName = "GetCustomerRequest")
        GetCustomerRequest getCustomerRequest);

    /**
     * 
     * @param updateCustomerRequest
     * @return
     *     returns northwind.domain.customer.UpdateCustomerResponse
     */
    @WebMethod(operationName = "UpdateCustomer")
    @WebResult(name = "UpdateCustomerResponse", targetNamespace = "http://domain.northwind/customer", partName = "UpdateCustomerResponse")
    public UpdateCustomerResponse updateCustomer(
        @WebParam(name = "UpdateCustomerRequest", targetNamespace = "http://domain.northwind/customer", partName = "UpdateCustomerRequest")
        UpdateCustomerRequest updateCustomerRequest);

    /**
     * 
     * @param createCustomerRequest
     * @return
     *     returns northwind.domain.customer.CreateCustomerResponse
     */
    @WebMethod(operationName = "CreateCustomer")
    @WebResult(name = "CreateCustomerResponse", targetNamespace = "http://domain.northwind/customer", partName = "CreateCustomerResponse")
    public CreateCustomerResponse createCustomer(
        @WebParam(name = "CreateCustomerRequest", targetNamespace = "http://domain.northwind/customer", partName = "CreateCustomerRequest")
        CreateCustomerRequest createCustomerRequest);

    /**
     * 
     * @param deleteCustomerRequest
     * @return
     *     returns northwind.domain.customer.DeleteCustomerResponse
     */
    @WebMethod(operationName = "DeleteCustomer")
    @WebResult(name = "DeleteCustomerResponse", targetNamespace = "http://domain.northwind/customer", partName = "DeleteCustomerResponse")
    public DeleteCustomerResponse deleteCustomer(
        @WebParam(name = "DeleteCustomerRequest", targetNamespace = "http://domain.northwind/customer", partName = "DeleteCustomerRequest")
        DeleteCustomerRequest deleteCustomerRequest);

}
